package com.moiza.moizaspringbootserver.domain.comment.mapper;

import com.moiza.moizaspringbootserver.comment.CommentAttatchmentFile;
import com.moiza.moizaspringbootserver.domain.comment.CommentAttatchmentFileEntity;

public interface CommentAttatchmentFileMapper {

	CommentAttatchmentFileEntity commentAttatchmentFileDomainToEntity(CommentAttatchmentFile commentAttatchmentFile);

	CommentAttatchmentFile commentAttatchmentFileEntityToDomain(CommentAttatchmentFileEntity commentAttatchmentFileEntity);
}
